name: Deployment
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  delete:
    branches: ['*']

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - name: Deployment
        uses: webNeat/hosty@main
        with:
          server_ip: ${{ secrets.VPS_IP }}
          server_user: ${{ secrets.VPS_USER }}
          ssh_private_key: ${{ secrets.VPS_SSH_KEY }}
          server_sudo_pass: ${{ secrets.VPS_PASS }}
          vars: |
            {
              "prod_env": ${{ toJSON(secrets.PROD_ENV) }}
            }
          handler: deployment.js