name: Remove from server
on:
  delete:
    branches: ['*']

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}
      - uses: actions/setup-node@v1
        with:
          node-version: 22
      - name: Install dependencies
        run: npm i
      - name: Add VPS to /etc/hosts
        run: echo "${{ secrets.VPS_IP }} vps" | sudo tee -a /etc/hosts
      - name: Add VPS to known_hosts
        run: ssh-keyscan -H vps >> ~/.ssh/known_hosts
      - name: Destroy with Ansible
        run: ANSIBLE_BECOME_PASS="${{ secrets.VPS_PASS }}" npm run destroy ${{ secrets.VPS_USER }} ${{ github.ref }}
